version: '3.3'

services:

  zipline:
    image: ghcr.io/diced/zipline
    ports:
      - '8200:3000'
    restart: unless-stopped
    environment:
      - CORE_RETURN_HTTPS=false
      - CORE_SECRET=my_secret_cambiar
      - CORE_HOST=0.0.0.0
      - CORE_PORT=3000
      - CORE_DATABASE_URL=postgres://User:p4ssw0rd@postgres/postgres
      - CORE_LOGGER=true
    volumes:
      - ./uploads:/zipline/uploads
      - ./public:/zipline/public
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_USER=User
      - POSTGRES_PASSWORD=p4ssw0rd
      - POSTGRES_DATABASE=postgres
    volumes:
      - ./pg_data:/var/lib/postgresql/data
